using Test
using Random
using Aqua
using JET
using Aletheia

module AletheiaGraphsImportSmoke
using Aletheia
using AletheiaGraphs
end

include("ownership.jl")

@testset "single-import focused accessors" begin
    alice = KGEntity(:alice)
    bob = KGEntity(:bob)
    edge_relation = KGRelation(:knows)
    graph = KnowledgeGraph([alice, bob], [edge_relation], [KGEdge(alice, edge_relation, bob)])
    @test frame(graph) isa Frame
    @test model(graph) isa Model
    @test relations(graph) == (edge_relation,)
    @test provenance(graph) == ()

    program = DSProgram([ProbabilisticFact(:rain, 1//2)])
    @test domain(program) == ()
    artifact = RuleArtifact([ArtifactRule(:rain, true)])
    @test rules(artifact) isa Vector

    graph_exports = Set(names(AletheiaGraphs; all=false))
    umbrella_exports = Set(names(Aletheia; all=false))
    shared = intersect(graph_exports, umbrella_exports)
    @test all(getfield(Aletheia, name) === getfield(AletheiaGraphs, name) for name in shared)

    @test all(isdefined(AletheiaGraphsImportSmoke, name) for name in shared)
end

@testset "umbrella public API" begin
    expected = Set{Symbol}([
        :Signature,
        :Formula,
        :FormulaPool,
        :Atom,
        :Branch,
        :DEFAULT_SIGNATURE,
        :DEFAULT_POOL,
        :atom,
        :branch,
        :children,
        :nchildren,
        :value,
        :operator,
        :head,
        :pool,
        :id,
        :isatom,
        :isbranch,
        :dag,
        :subterms,
        :nsubterms,
        :signature,
        :connectives,
        :arity,
        :dual,
        :hasconnective,
        :hasdual,
        :precedence,
        :associativity,
        :iscommutative,
        :ismodal,
        :isunary,
        :isdiamond,
        :isbox,
        :isgrounded,
        :notation,
        :relation,
        :syntaxstring,
        :AbstractRelationalConnective,
        :Negation,
        :Conjunction,
        :Fusion,
        :Disjunction,
        :Implication,
        :Diamond,
        :Box,
        :NEGATION,
        :CONJUNCTION,
        :FUSION,
        :DISJUNCTION,
        :IMPLICATION,
        :¬,
        :∧,
        :⊗,
        :∨,
        :→,
        :TruthAlgebra,
        :BooleanAlgebra,
        :GodelAlgebra,
        :LukasiewiczAlgebra,
        :FiniteTruth,
        :FiniteFLewAlgebra,
        :BooleanFLewAlgebra,
        :G3,
        :G4,
        :G5,
        :G6,
        :Ł3,
        :Ł4,
        :H4,
        :H6,
        :H6_1,
        :H6_2,
        :H6_3,
        :H9,
        :RelationFamily,
        :IntervalRelation,
        :PointRelation,
        :RCCRelation,
        :RectangleRelation,
        :relation_holds,
        :relation_successors,
        :inverse,
        :converse,
        :rectangle_relation,
        :globalrel,
        :identityrel,
        :GlobalRelation,
        :IdentityRelation,
        :AtWorldRelation,
        :ToCenterRelation,
        :tocenterrel,
        :centralworld,
        :emptyworld,
        :isgrounding,
        :Interval,
        :Rectangle,
        :Point,
        :interval_frame,
        :rectangle_frame,
        :point_frame,
        :BEFORE,
        :MEETS,
        :OVERLAPS,
        :STARTS,
        :DURING,
        :FINISHES,
        :EQUALS,
        :AFTER,
        :MET_BY,
        :OVERLAPPED_BY,
        :STARTED_BY,
        :CONTAINS,
        :FINISHED_BY,
        :ALLEN_RELATIONS,
        :IDENTITY,
        :MINIMUM,
        :MAXIMUM,
        :SUCCESSOR,
        :PREDECESSOR,
        :GREATER,
        :LESSER,
        :POINT_RELATIONS,
        :DC,
        :EC,
        :PO,
        :TPP,
        :TPPi,
        :NTPP,
        :NTPPi,
        :RCC_EQ,
        :RCC8_RELATIONS,
        :RCC8_BASICS,
        :DR,
        :PP,
        :PPi,
        :RCC5_RELATIONS,
        :RCC5Relation,
        :FrameClass,
        :K,
        :T,
        :S4,
        :S5,
        :REFLEXIVE,
        :TRANSITIVE,
        :SYMMETRIC,
        :SERIAL,
        :isreflexive,
        :istransitive,
        :issymmetric,
        :isserial,
        :reflexive,
        :transitive,
        :symmetric,
        :serial,
        :satisfies,
        :axioms,
        :axiom,
        :validates,
        :BOOLEAN,
        :truth_type,
        :carrier,
        :top,
        :bottom,
        :bot,
        :meet,
        :join,
        :fusion,
        :domain,
        :implication,
        :negation,
        :levels,
        :isfinitechain,
        :precedeq,
        :precedes,
        :succeedeq,
        :succeeds,
        :maximalmembers,
        :minimalmembers,
        :AbstractFrame,
        :AbstractUniModalFrame,
        :AbstractMultiModalFrame,
        :AbstractWorld,
        :AbstractWorlds,
        :AnyWorld,
        :Frame,
        :worlds,
        :relations,
        :hasworldindex,
        :world_position,
        :accessible,
        :collateworlds,
        :check,
        :extension,
        :describe,
        :EvaluationCache,
        :clear!,
        :Valuation,
        :ValuationCallback,
        :Model,
        :frame,
        :algebra,
        :valuation,
        :interpret,
        :AbstractModelFamily,
        :ModelFamily,
        :instance_count,
        :eachinstance,
        :instance_model,
        :AbstractScalarDataset,
        :AbstractScalarFeature,
        :AbstractScalarCondition,
        :AbstractAggregateMemo,
        :ThresholdCondition,
        :DenseFeatureStore,
        :PreparedScalarData,
        :ScalarWorldDomainError,
        :MixedAlgebraError,
        :AggregateMemoStore,
        :ScalarEvaluationCache,
        :ScalarRelationIndex,
        :prepare_scalar,
        :feature_value,
        :scalar_check,
        :scalar_atom_values,
        :scalar_valuation,
        :scalar_family,
        :aggregate_value,
        :representative_worlds,
        :data_version,
        :batch_apply,
        :source,
        :store,
        :relation_index,
        :feature_index,
        :instance_index,
        :features,
        :instances,
        :world_index,
        :instance_frame,
        :uniform_frame,
        :isuniform,
        :FirstOrderTerm,
        :FirstOrderFormula,
        :Variable,
        :Constant,
        :FunctionTerm,
        :Predicate,
        :Equality,
        :FONegation,
        :FOConjunction,
        :FODisjunction,
        :FOImplication,
        :Exists,
        :Forall,
        :FirstOrderInterpretation,
        :evaluate,
        :standard_translation,
        :first_order_interpretation,
        :Literal,
        :literal,
        :positive_literal,
        :negative_literal,
        :atoms,
        :literals,
        :clauses,
        :Clause,
        :HornClause,
        :ClauseSet,
        :Substitution,
        :substitute,
        :subsumes,
        :more_general,
        :more_specific,
        :equivalent_under_subsumption,
        :ishorn,
        :downward_refinements,
        :upward_refinements,
        :generalizations,
        :HypothesisScore,
        :score,
        :ILPExample,
        :EntailmentExample,
        :InterpretationExample,
        :ProofExample,
        :learning_from_entailment,
        :learning_from_interpretations,
        :learning_from_proofs,
        :interpretation_example,
        :model_example,
        :iscnf,
        :isdnf,
        :to_cnf,
        :to_dnf,
        :bisimilar,
        :BisimulationClass,
        :BisimulationContraction,
        :QuotientModel,
        :bisimulation_contraction,
        :contraction_world,
        :model,
        :classes,
        :world_map,
        :AbstractProver,
        :ProverResult,
        :PropositionalProver,
        :FiniteModelProver,
        :BoundedFiniteProver,
        :prove,
        :prove_valid,
        :prove_entails,
        :issatisfiable,
        :isvalid,
        :entails,
        :SoleLogics,
        :SymbolicArtifact, :ArtifactState, :ArtifactOperation, :ArtifactCase, :Provenance,
        :TraceStep, :ExecutionTrace, :VerificationReport, :MetricValue, :MetricBundle,
        :AuditRecord, :ArtifactRule, :RuleArtifact, :TreeArtifact, :eval_artifact,
        :extract_artifact, :inject!, :verify_artifact, :metric_bundle, :audit, :replay,
        :serialize_trace, :deserialize_trace, :stable_hash, :provenance, :rules, :nodes,
        :test_interface, :NeSyContractError, :InvalidNeuralValueError, :MalformedCaseError,
        :SemanticLossError, :ChoiceLabelError, :NeuralLeafValuation, :SKERoundTrip,
        :neural_valuation, :neural_choice_labels, :ske_roundtrip, :semantic_loss,
    ])
    union!(
        expected,
        Set([
            :AletheiaCircuits,
            :AletheiaGraphs,
            :AbstractKGEntity,
            :AbstractKGRelation,
            :KGEntity,
            :KGRelation,
            :KGProvenance,
            :KGEdge,
            :KnowledgeGraph,
            :KGPath,
            :KGSubgraph,
            :paths,
            :subgraphs,
            :path_valid,
            :path_validity,
            :path_provenance,
            :concept_atoms,
            :concept_extension,
            :entities,
            :edges,
            :ChoiceVariable,
            :AbstractChoiceVariable,
            :ChoiceAlternative,
            :ChoiceLiteral,
            :ProbabilisticFact,
            :GroundRule,
            :DSProgram,
            :AbstractDSProgram,
            :DSProfile,
            :DSQuery,
            :DSWorld,
            :alternatives,
            :weights,
            :choice_id,
            :facts,
            :choices,
            :rules,
            :total_choices,
            :choice_probability,
            :ground,
            :validate_program,
            :world,
            :query_event,
            :compile_event,
            :AbstractEvent,
            :EventSpec,
            :AbstractEventCircuit,
            :CircuitNode,
            :BDDNode,
            :BDD,
            :CircuitCertificate,
            :CertifiedCircuit,
            :CompiledEvent,
            :support,
            :source_provenance,
            :validate,
            :variable_order,
            :roots,
            :nodes,
            :EventNot,
            :EventAnd,
            :EventOr,
            :Not,
            :And,
            :Or,
            :not_event,
            :and_event,
            :or_event,
            :CircuitError,
            :UnsupportedFeatureError,
            :ProgramValidationError,
            :UnnormalizedWeightsError,
            :ZeroMassEvidenceError,
            :UncertifiedCircuitError,
            :InvalidCircuitError,
            :InvalidProbabilityError,
            :GroundingError,
            :OwnershipError,
            :MixedAlgebraError,
            :AbstractCommutativeSemiring,
            :ProbabilitySemiring,
            :ProbabilityProfile,
            :Float64Profile,
            :RationalProfile,
            :add,
            :mul,
            :literal_label,
            :neutral_sum,
            :amc,
            :wmc,
            :conditional_probability,
        ]),
    )
    @test Set(setdiff(names(Aletheia; all=false), [:Aletheia])) == expected
    @test Aletheia.AletheiaCore isa Module
    @test Aletheia.AletheiaData isa Module
    @test Aletheia.AletheiaLearn isa Module
    @test Aletheia.AletheiaSole isa Module
    @test Aletheia.AletheiaCircuits isa Module
    @test Aletheia.AletheiaGraphs isa Module
end

include("umbrella_presentation.jl")
include("citations.jl")
include("examples.jl")
include("showcase.jl")
include("benchmark_load_gate.jl")
include("benchmark_measurement.jl")

@testset "Aletheia" begin
    Aqua.test_all(Aletheia)
    if pkgversion(JET) < v"0.11"
        JET.test_package(Aletheia; target_defined_modules=true)
    else
        JET.test_package(
            Aletheia; target_modules=(Aletheia,), analyze_from_definitions=true
        )
    end
end
